// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIoROjzpMsTXsLnb4K73yYMaCIZhS3w4',
    appId: '1:1058223851177:web:b80379c2cbb30226bfcbb8',
    messagingSenderId: '1058223851177',
    projectId: 'librasync-2b2fc',
    authDomain: 'librasync-2b2fc.firebaseapp.com',
    storageBucket: 'librasync-2b2fc.firebasestorage.app',
    measurementId: 'G-RGE57MMELC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtkg0yOzNcRM8Bt-Fs2a8JN7hnSHkn1o',
    appId: '1:1058223851177:android:0576e3db32ef9401bfcbb8',
    messagingSenderId: '1058223851177',
    projectId: 'librasync-2b2fc',
    storageBucket: 'librasync-2b2fc.firebasestorage.app',
  );
}
